[package]
name = "gift_shop"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
tap = "1.0.1"
winnow = "0.7.14"

[dev-dependencies]
rstest = "0.26.1"
