[package]
name = "printing_department"
version = "0.1.0"
edition = "2024"

[dependencies]
im-rc = { version = "15.1.0", features = ["rayon"] }
itertools = "0.14.0"
rayon = "1.11.0"
tap = "1.0.1"
winnow = "0.7.14"
